### ISSUE TITLE
ES cluster on Tutum?

### ISSUE THREAD

**Issue by alan-czajkowski** [fabric8io/elasticsearch-cloud-kubernetes#10]
i know this is not the appropriate place to post this, but is there any chance an ES plugin could be created for Tutum?
https://www.tutum.co/

**Comment by jimmidyson** [comment]
Hi @alan-czajkowski,

Sorry as I'm not a tutum user it's not something I have time to work on. Feel free to use this plugin as a base for your own tutum cloud plugin though.

Sorry!
