### ISSUE TITLE
Support for elasticsearch 5.5.1

### ISSUE THREAD

**Issue by quickwind** [fabric8io/elasticsearch-cloud-kubernetes#100]
When will be the support for es 5.5.1?

**Comment by jimmidyson** [comment]
We'd appreciate a PR if you feel like submitting one?

**Comment by jperville** [comment]
@jimmidyson a PR already exists, waiting to be merged, see #99.

**Comment by jcantrill** [comment]
Released 
Tue Aug 08 2017 13:50:27 GMT-0400 (EDT)
