### ISSUE TITLE
Support for 6.0.0-rc1 

### ISSUE THREAD

**Issue by tuxx** [fabric8io/elasticsearch-cloud-kubernetes#108]
I would like to test this plugin with elasticsearch 6.0.0-rc1. I tried compiling it myself but i get all kinds of errors when changing the the version and elasticsearch.version in pom.xml. 

Has anyone tried compiling this for 6.0.0 and got it working?

`
[ERROR] /home/tuxx/code/elasticsearch-cloud-kubernetes/src/main/java/io/fabric8/elasticsearch/plugin/discovery/kubernetes/KubernetesDiscoveryPlugin.java:[72,7] constructor ZenDiscovery in class org.elasticsearch.discovery.zen.ZenDiscovery cannot be applied to given types;
  required: org.elasticsearch.common.settings.Settings,org.elasticsearch.threadpool.ThreadPool,org.elasticsearch.transport.TransportService,org.elasticsearch.common.io.stream.NamedWriteableRegistry,org.elasticsearch.cluster.service.MasterService,org.elasticsearch.cluster.service.ClusterApplier,org.elasticsearch.common.settings.ClusterSettings,org.elasticsearch.discovery.zen.UnicastHostsProvider,org.elasticsearch.cluster.routing.allocation.AllocationService,java.util.Collection<java.util.function.BiConsumer<org.elasticsearch.cluster.node.DiscoveryNode,org.elasticsearch.cluster.ClusterState>>
  found: org.elasticsearch.common.settings.Settings,org.elasticsearch.threadpool.ThreadPool,org.elasticsearch.transport.TransportService,org.elasticsearch.common.io.stream.NamedWriteableRegistry,org.elasticsearch.cluster.service.ClusterService,org.elasticsearch.discovery.zen.UnicastHostsProvider
  reason: actual and formal argument lists differ in length
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.274 s
[INFO] Finished at: 2017-10-11T13:46:31+02:00
[INFO] Final Memory: 25M/404M
[INFO] ------------------------------------------------------------------------
`

**Comment by amir20001** [comment]
GH-109 should fix that

**Comment by tuxx** [comment]
Thanks alot :)
