### ISSUE TITLE
is this project abandoned ? can't find 6.1 resources

### ISSUE THREAD

**Issue by prune998** [fabric8io/elasticsearch-cloud-kubernetes#120]
can't find 6.x plugins
can't find 6.x images on dockerhub
can't build plugin package for 6.x

```
git checkout elasticsearch-cloud-kubernetes-6.1.2
mvn clean package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Elasticsearch Kubernetes cloud plugin 6.1.2
[INFO] ------------------------------------------------------------------------
...
```

Then : 
```
elasticsearch-plugin list
discovery-kubernetes
WARNING: plugin [discovery-kubernetes] is incompatible with version [6.1.1]; was designed for version [5.5.2]
```

Am I missing something ?

**Comment by richm** [comment]
> Am I missing something ?

The team is primarily focused on 5.x for https://github.com/openshift/origin-aggregated-logging
PRs for 6.x support are welcome

**Comment by prune998** [comment]
Well, I reverted to 5.5.2... working as expected :)
I'll try some PRs when I move from Go to Java, maybe later when I'm dead :p 

BTW, thanks for all your good work !

**Comment by jcantrill** [comment]
@prune998 Please be patient... We are working to resolve publishing rights for this project

**Comment by pkrishnath** [comment]
same issue here. i was looking for 6.2.2 and failed for same reason
Read me file description is confusing !!!!

**Comment by juan131** [comment]
Hi @richm @jcantrill 

I created a PR https://github.com/fabric8io/elasticsearch-cloud-kubernetes/pull/123 to update the plugin for ES 6.2.3 that was already merged. Could you release a new version please for that version? 

Thanks in advance!

**Comment by jcantrill** [comment]
@juan131 I can post a released version to this repo but am still working through getting permissions to publish to mvn.  Is this an acceptable way for you to consume the artifact?

**Comment by juan131** [comment]
Hi @jcantrill 

In order to install it on ES following the standard approach it should be published at:
https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes

It would be great if you could publish it there. 

In the meantime, I can try to implement a workaround so I download the plugin from GitHub.

Thanks again!

**Comment by Battleroid** [comment]
Yep, if it can be published on Maven that'd be great.

**Comment by jcantrill** [comment]
@juan131 @Battleroid  I believe you are missing what I said in previous comments.  I am still working to get permissions to publish to maven;  I am fully aware maven.org is the desired destination.  Elasticsearch plugin install will accept a url to the artifact  which can be file, http, etc.  If you need it before I am able to establish permissions, I am more then happy to publish as a github release.

**Comment by jcantrill** [comment]
@juan131 Best I can do for you for the time being https://github.com/fabric8io/elasticsearch-cloud-kubernetes/files/1898895/elasticsearch-cloud-kubernetes-6.1.3.zip

@prune998 I don't have information regarding the images.  @maxandersen This is another area where we require ownership to ensure those images are produced

**Comment by jcantrill** [comment]
Closing as we have viable source for the artifact until the maven bits can be sorted out.

**Comment by jcantrill** [comment]
@calinah Try this one:  https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-6.1.2.1

**Comment by calinah** [comment]
@jcantrill I get this now:
```
/usr/share/elasticsearch/bin/elasticsearch-plugin install  https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-6.1.2.1
-> Downloading https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-6.1.2.1
ERROR: `elasticsearch` directory is missing in the plugin zip
```

**Comment by jcantrill** [comment]
@calinah Let me check it.  I installed it locally with now issue

**Comment by jcantrill** [comment]
@calinah Did you try using the URL to the actual zip: https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/download/elasticsearch-cloud-kubernetes-6.1.2.1/elasticsearch-cloud-kubernetes-6.1.2.1.zip

```
$ unzip -l elasticsearch-cloud-kubernetes-6.1.2.1.zip
Archive:  elasticsearch-cloud-kubernetes-6.1.2.1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-11-2018 15:24   elasticsearch/
  5674268  04-11-2018 15:19   elasticsearch/kubernetes-model-1.0.65.jar
     1035  04-11-2018 15:18   elasticsearch/plugin-security.policy
    34577  10-26-2016 15:01   elasticsearch/jackson-module-jaxb-annotations-2.7.5.jar
    50894  10-26-2016 15:01   elasticsearch/jackson-annotations-2.7.0.jar
  1208844  05-01-2017 15:25   elasticsearch/jackson-databind-2.7.7.jar
      825  01-18-2017 16:24   elasticsearch/plugin-descriptor.properties
    63777  10-26-2016 15:01   elasticsearch/validation-api-1.1.0.Final.jar
   344481  03-06-2018 17:20   elasticsearch/okhttp-3.4.1.jar
    76036  08-12-2016 12:16   elasticsearch/okio-1.9.0.jar
    35518  05-01-2017 15:25   elasticsearch/zjsonpatch-0.3.0.jar
    16310  04-11-2018 15:24   elasticsearch/elasticsearch-cloud-kubernetes-6.1.2.1.jar
   345062  04-11-2018 15:18   elasticsearch/kubernetes-client-1.4.35.jar
     8081  03-06-2018 17:20   elasticsearch/logging-interceptor-3.4.1.jar
    26091  03-06-2018 17:20   elasticsearch/okhttp-ws-3.4.1.jar
    33088  02-27-2017 15:46   elasticsearch/slf4j-api-1.7.13.jar
     4595  10-26-2016 15:01   elasticsearch/jul-to-slf4j-1.7.13.jar
    13911  10-26-2016 15:01   elasticsearch/generex-1.0.1.jar
   176285  10-26-2016 15:01   elasticsearch/automaton-1.11-8.jar
---------                     -------
  8113678                     19 files

```
