### ISSUE TITLE
elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:6.2.3

### ISSUE THREAD

**Issue by jfborie** [fabric8io/elasticsearch-cloud-kubernetes#125]
FileNotFoundException: https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-
kubernetes/6.2.3/elasticsearch-cloud-kubernetes-6.2.3.zip

Can you push the file to maven?

**Comment by datarace** [comment]
+1

**Comment by jcantrill** [comment]
6.2.3.1 pushed to maven via proper release workflow.  Please reopen if you have issues.

**Comment by juan131** [comment]
Thanks @jcantrill I can confirm it's working using version 6.2.3.1! 👏
