### ISSUE TITLE
Release for 5.6.9

### ISSUE THREAD

**Issue by ron1** [fabric8io/elasticsearch-cloud-kubernetes#131]
Please release 5.6.9 version of plugin. See prerequisite PR https://github.com/fabric8io/elasticsearch-cloud-kubernetes/pull/130.

**Comment by ron1** [comment]
I see prereq PR was committed to 5.6.x branch. Thanks. Do you have an ETA for releasing 5.6.9?

**Comment by jcantrill** [comment]
Done. I should be available in the public repos in the next several hours
