### ISSUE TITLE
Discovery by label on Elasticsearch 5.x

### ISSUE THREAD

**Issue by ruippeixotog** [fabric8io/elasticsearch-cloud-kubernetes#138]
I see that #98 added support for discovery by label - a thing that I need, since I'm using Deployments and I need the readiness check to be failing in order for the deployment not to kill all old instances as soon as the new ones boot.

However, I can't see the feature in the latest version of the plugin. Is there any limitation I'm not aware of? Can this be ported to ES 5.x?

**Comment by jcantrill** [comment]
It can.  PRs are welcome.  Also consider #94 where you may not even need this plugin

**Comment by ruippeixotog** [comment]
Using only zen would be great! But what exactly would be the hostname I'd use to lookup all the pod IPs inside the cluster? ClusterIP services expose a hostname like `elasticsearch.default.svc.cluster.local`, but it points to a single IP - the IP of the service - from which requests are routed at the IP layer to the pod IPs.

**Comment by jcantrill** [comment]
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

**Comment by ruippeixotog** [comment]
Oh, nice! I'm still a beginner using Kubernetes and I never explored those types of services. They seem to do the trick for discovery, yeah. Will try them later. Thanks again!

**Comment by jcantrill** [comment]
@ruippeixotog see #140
