### ISSUE TITLE
Release 2.0 support

### ISSUE THREAD

**Issue by pires** [fabric8io/elasticsearch-cloud-kubernetes#17]
Just so I (and possibly others) know when this is released.

**Comment by jimmidyson** [comment]
Done! Yay! http://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/2.0.0/

Please report any issues ASAP. I'll get working on tests some time, unless someone else wants to contribute?

**Comment by pires** [comment]
Amazing job, @jimmidyson! Kudos.
