### ISSUE TITLE
Release in Maven central

### ISSUE THREAD

**Issue by pires** [fabric8io/elasticsearch-cloud-kubernetes#2]
This way anyone can use this directly in their Elasticsearch deployments.

For instance, in a ```Dockerfile```:
```
ADD http://central.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/1.0.0/elasticsearch-cloud-kubernetes-1.0.0.jar /data/plugins/
```

**Comment by pires** [comment]
I just realized the plug-in itself needs dependencies, so it should be come something like:
```
ADD http://central.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/1.0.0/elasticsearch-cloud-kubernetes-1.0.0.zip
```

Right?

**Comment by jimmidyson** [comment]
Yes that's right. As with all Elasticsearch plugins, the zip contains
required dependencies & needs to be deployed rather than a single JAR.

**Comment by jimmidyson** [comment]
Released & available at http://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/1.0.0/

**Comment by pires** [comment]
Thanks @jimmidyson!
