### ISSUE TITLE
fabric8/elasticsearch-k8s requires non-random user

### ISSUE THREAD

**Issue by jpechane** [fabric8io/elasticsearch-cloud-kubernetes#26]
If this image is run in OpenShift production environment as part of apiman application then it requires to be run as non-restricted container. So far I am using serviceAccount that belongs to privileged security context and runs as user id 0. The image should be able to run as any random UID.
It fails in starting script when it tries to do a chown.

apiman uses fabric8/elasticsearch-k8s:1.6.0 image

**Comment by jimmidyson** [comment]
This should work with arbitrary uid now.
