### ISSUE TITLE
Where is the Dockerfile for your fabric8/elasticsearch-k8s image?

### ISSUE THREAD

**Issue by chrissnell** [fabric8io/elasticsearch-cloud-kubernetes#28]
I've looked everywhere for the Dockerfile that y'all are using to build the elasticsearch-k8s image but can't find it.  Can somebody add it to this repo or other GH repo?

**Comment by pires** [comment]
@chrissnell build takes care of generating it. See from https://github.com/fabric8io/elasticsearch-cloud-kubernetes/blob/master/pom.xml#L217.

**Comment by jimmidyson** [comment]
Also see https://github.com/fabric8io/elasticsearch-cloud-kubernetes/blob/master/src/main/docker/Dockerfile which generates an intermediate Elasticsearch that works with arbitrary uids (security!). The final image just has the plugin added automatically from the build, but no Dockerfile is used for that.

**Comment by chrissnell** [comment]
Thanks!
