### ISSUE TITLE
Is 2.2.0 supposed to work with java security manager enabled?

### ISSUE THREAD

**Issue by vaijab** [fabric8io/elasticsearch-cloud-kubernetes#29]

**Comment by jimmidyson** [comment]
Sorry adding the security manager config to the plugin hasn't been done yet. Contribution very welcome.

**Comment by jimmidyson** [comment]
Thanks for the pointer. If anyone is able to send in a PR to fix this it would be most appreciated.

**Comment by pires** [comment]
On it.

**Comment by vaijab** [comment]
@pires thanks for that!
