### ISSUE TITLE
Add service option alternative to selector

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/elasticsearch-cloud-kubernetes#4]
To use the selector from the specified service instead.

**Comment by pires** [comment]
I'm not sure I agree with this.

In my case, I follow ES best-practice of separating my nodes in 3 groups:
* Masters (no data, no HTTP, just transport)
* Load-balancers (no data, just HTTP + transport)
* Data nodes (just data + transport)
So now, I want to things:
* Clients will use load-balancers alone, thus I need to provide a service for accessing this
* The service, ofc, must define a selector that picks load-balancers *only* (smth like ```{"component":"elasticsearch", "role":"load-balancer"}```
* All nodes must find each other, and for this I use the selector ```json {"component":"elasticsearch"}```

Concluding, I shall not use a service for finding nodes that are not related to services but rather just to replication controllers.

**Comment by jimmidyson** [comment]
Good points, thanks. Closing after this feedback.
