### ISSUE TITLE
Support for ES 5.1.1?

### ISSUE THREAD

**Issue by yaron-idan** [fabric8io/elasticsearch-cloud-kubernetes#56]
Using this plugin with ES 5.0.1 and enjoying it greatly, I was curious to know is support for ES 5.1.1 that was launched next week coming up, and if so when?

Thanks,
Yaron.

**Comment by pires** [comment]
Elasticsearch 5.1.x is not trivial since the plug-in spec as changed from 2.x to 5.x, and while 5.0.x supported the 2.x way of doing things, this is no longer the case with 5.1.x.

I'll be looking into it but feel free to open a PR.
