### ISSUE TITLE
Failed to install plugin for Elasticsearch 2.4.1

### ISSUE THREAD

**Issue by qianzhangxa** [fabric8io/elasticsearch-cloud-kubernetes#60]
I can not install this plugin for Elasticsearch 2.4.1:
```
# bin/plugin install io.fabric8:elasticsearch-cloud-kubernetes:2.4.1 --verbose        
-> Installing io.fabric8:elasticsearch-cloud-kubernetes:2.4.1...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1/2.4.1/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1-2.4.1.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1/2.4.1/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1-2.4.1.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1/2.4.1/io.fabric8:elasticsearch-cloud-kubernetes:2.4.1-2.4.1.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```

It seems this 2.4.1 plugin can not be found, can anyone please help?

**Comment by jimmidyson** [comment]
Try replacing the colons with forward slashes.

**Comment by qianzhangxa** [comment]
Yes, it works! Thanks a lot!

But can you please let me know why replacing the colons with forward slashes can fix this issue?

**Comment by jimmidyson** [comment]
The plugin is distributed via maven central and that is the documented way to install plugins from maven central (https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/installation.html#_community_and_non_core_plugins).

**Comment by qianzhangxa** [comment]
But previously (months ago), I can install the plugin with colons in that command, just recently I found I failed to install it.

And I think the README.md of this repo may need to be updated. Currently it has an example like this:
```
elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:5.1.1
```
We need to replace the colons with forward slashes in it as well?

**Comment by jcantrill** [comment]
@qianzhangxa Please consider submitting a PR if there is a documentation issue.
