### ISSUE TITLE
Build for ElasticSearch v5.1.2

### ISSUE THREAD

**Issue by jperville** [fabric8io/elasticsearch-cloud-kubernetes#62]
Hello,

Would it be possible to release a version of this plugin compiled for ES [v5.1.2](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/release-notes-5.1.2.html)? Only v5.1.1 is listed on Maven Central.

Thank you in advance.

**Comment by speedplane** [comment]
Version 5.2.0 just came out, would be nice to see a build for that as well.

**Comment by pires** [comment]
Feel free to open a PR.

**Comment by speedplane** [comment]
Done https://github.com/fabric8io/elasticsearch-cloud-kubernetes/pull/71
