### ISSUE TITLE
Invalid plugin version in docker image

### ISSUE THREAD

**Issue by thomastaylor312** [fabric8io/elasticsearch-cloud-kubernetes#72]
Not sure if this is the correct repo for this, but the 5.2.0 image does not have the correct version of elasticsearch installed:

```
uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Plugin [discovery-kubernetes] is incompatible with Elasticsearch [5.1.1]. Was designed for version [5.2.0]
```

```
elasticsearch@b4e01e29e890:/usr/share/elasticsearch$ elasticsearch --version
Version: 5.1.1, Build: 5395e21/2016-12-06T12:36:15.409Z, JVM: 1.8.0_111
```

**Comment by huangfushun** [comment]
please fix incompatible version with images 2.4.4

**Comment by prashantchitta** [comment]
I am getting the same error that @thomastaylor312 got. I am currently using https://hub.docker.com/r/fabric8/elasticsearch-k8s/tags/ 5.2.0 version. Is there any plan to upgrade the image with the fix?
cc @pires @jimmidyson

**Comment by metal3d** [comment]
as @huangfushun same problem on 2.4.4
