### ISSUE TITLE
Push 2.3.5 to Docker Hub

### ISSUE THREAD

**Issue by fmatoss** [fabric8io/elasticsearch-cloud-kubernetes#81]
There is a release for this version, but it's not in Docker Hub registry.

https://hub.docker.com/r/fabric8/elasticsearch-k8s/tags/
https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-2.3.5

**Comment by jcantrill** [comment]
@fmatoss Do you need 2.3.5 or can you use 2.4.4?

**Comment by fmatoss** [comment]
I had this need because of some apps using elastic4s lib in scala 2.10, their latest compatible client is for version 2.3.x (https://github.com/sksamuel/elastic4s#release)

But now I am not running ES in kubernetes, nobody reacted to this issue after almost an year, I think no one else needs this, so you can ignore/close this issue if you want.
