### ISSUE TITLE
Document advantage over headless service discovery

### ISSUE THREAD

**Issue by jimmyjones2** [fabric8io/elasticsearch-cloud-kubernetes#94]
The Elasticsearch docs for discovery.zen.ping.unicast.hosts says:
> If a hostname lookup resolves to multiple IP addresses then each IP address will be used for discovery

Given this is exactly what a headless kubernetes service would create, what is the advantage of using this plugin?

**Comment by jcantrill** [comment]
@t0ffel Can you comment on this?  Are you not evaluating the need or not needing this plugin because of question being asked

**Comment by t0ffel** [comment]
@jcantrill I'm going to test this according to https://github.com/RHsyseng/docker-rhel-elasticsearch/pull/22 in our internal staging environment, if it works out I suggest that we gradually move toward that.

**Comment by jcantrill** [comment]
@t0ffel Can you provide details here of how to set this up.  If works as advertised I would advocate recommending users to move to that pattern over the use of this plugin.

**Comment by jcantrill** [comment]
Closing in favor of #140
