### ISSUE TITLE
5.5.0 not in maven repo

### ISSUE THREAD

**Issue by bambash** [fabric8io/elasticsearch-cloud-kubernetes#97]
I see on the readme that you have:
```elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:5.5.0```

the package doesn't exist yet in maven:
https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/

any idea when it will be pushed?

Thanks!

**Comment by marcofranssen** [comment]
I did the PR to upgrade this package to 5.5.0. Also waiting for this plugin to become available on maven.

**Comment by jimmidyson** [comment]
Sorry just kicked release now.

**Comment by r4j4h** [comment]
Looks good, but want to point out before we close this that 5.5.1 is out. Seems like not many changes needed here, just to be pushed.

**Comment by jcantrill** [comment]
Released Wed Jul 19 2017 09:12:41 GMT-0400 (EDT).
